conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .forms import LoginForm
from . import views

urlpatterns = [
    path("", views.index, name="home"),
    path("contact/", views.contact, name="contact"),
    path("signup/", views.signup, name="signup"),
    path("login/", auth_views.LoginView.as_view(template_name="core/login.html",authentication_form=LoginForm), name="login"),
] 

items/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('<int:pk>/', views.details, name='detail'),
    path('new/', views.new_item, name='new'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),

]

puddle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("items/", include("items.urls")),
    path("dashboard/", include("dashboard.urls")),
    path('conversation/', include('conversation.urls')),
] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

items/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Item(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    is_sold = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, related_name="items" ,on_delete=models.CASCADE)
    category = models.ForeignKey(Category, related_name="items", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} By {self.created_by}"

items/forms.py
from django import forms

from .models import Item, Category

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price',)
        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            })
        }


class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'price', 'is_sold',)
        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
        }

items/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from .models import Item, Category
from .forms import ItemForm, EditItemForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def items(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    items = Item.objects.filter(is_sold=False)

    if category_id:
        items = items.filter(category_id=category_id)

    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))

    return render(request, 'items/items.html', {
        'items': items,
        'query': query,
        'categories': categories,
        'category_id': int(category_id)
    })

def details(request, pk):
    item = Item.objects.get(pk=pk)
    related_item = Item.objects.filter(
        category=item.category).exclude(pk=pk)[:3]

    context = {"item": item, "related_item": related_item}
    return render(request, "items/details.html", context)


@login_required
def new_item(request):
    form = ItemForm()
    if request.method == 'POST':
        form = ItemForm(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()

            return redirect('item:detail', pk=item.id)
        else:
            form = ItemForm()
    context = {"form": form}
    return render(request, "items/new_item.html", context)

@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)

    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)

        if form.is_valid():
            form.save()
            return redirect('item:detail', pk=item.id)
    else:
        form = EditItemForm(instance=item)  # Define the form here

    context = {"form": form}
    return render(request, "items/form.html", context)


@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()

    return redirect('dashboard:index')

items/templates/items/details.html
{% extends "base.html" %}

{% block content %}
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-6">
        {% if item.images %}
        {% endif %}
        <div class="md:col-span-2 lg:col-span-3 p-6 bg-gray-100 rounded-xl">
            <h1 class="mb-6 text-2xl md:text-3xl lg:text-4xl">
                {{ item.name }}
            </h1>
            <p class="mb-6 text-gray-500">
                <strong>Price:</strong> {{ item.price }}
            </p>
            <p class="mb-6 text-gray-500">
                <strong>Seller:</strong> {{ item.created_by.username }}
            </p>
            {% if item.description %}
                <p class="mb-6 text-gray-700">
                 <strong class="text-gray-500">Description:</strong><br>
                 {{ item.description }}
                </p>
            {% endif %}
            {% if request.user == item.created_by %}
            <div class="mt-6 p-6 rounded-xl">
                <p class="text-lg font-bold">Your Item</p>
                <a href="{% url 'item:edit' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl">Edit</a>
                <span class="m-2"></span>
                <a href="{% url 'item:delete' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Delete</a>
            </div>
        {% else %}  
            <a href="{% url "conversation:new" item.id%}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Contact seller</a>
        {% endif %}
        </div>
    </div>
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Related Items</h2>
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
          {% for item in related_item %}
            <div>
                <a href="{% url "item:detail" item.id%}" class="block rounded-xl overflow-hidden bg-white hover:shadow-md">
                    <div>
                        {% if item.images %}
                            <img src="{{ item.images.url }}" alt="{{ item.name }}" class="rounded-t-xl w-full">
                        {% endif %}
                    </div>
                    
                    <div class="p-6">
                        <h3 class="text-xl md:text-2xl">{{ item.name }}</h3>
                        <p class="text-gray-500">${{ item.price }}</p>    
                    </div>
                </a>
            </div>
          {% endfor %}
        </div>
    </div>
{% endblock %}

items/templates/items/form.html
{% extends "base.html" %}

{% block content %}

<div class="w-full md:w-2/3 my-6 p-6 mx-auto rounded-xl bg-gray-100">
    <h1 class="mb-6 text-2xl md:text-3xl">Edit Item</h1>

    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}

        <div class="space-y-4">
            {{ form.as_p }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mt-6 p-4 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="mt-6 py-3 px-6 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

items/templates/items/items.html
{% extends 'base.html' %}

{% block content %}
    <div class="pb-6 grid grid-cols-1 md:grid-cols-4 gap-4 bg-gray-100">
        <div class="md:col-span-1 mt-16 md:mt-0 ">
            <form method="get" action="{% url 'item:items' %}">
                <input name="query" class="w-full py-3 px-4 md:px-6 border rounded-xl" type="text" value="{{ query }}" placeholder="Find a bike, a chair or car...">

                <button class="mt-2 py-3 px-6 text-lg bg-teal-500 text-white rounded-xl">Search</button>
            </form>

            <hr class="my-6">

            <p class="font-semibold">Categories</p>

            <ul>
                {% for category in categories %}
                    <li class="py-2 px-2 rounded-xl{% if category.id == category_id %} bg-gray-200{% endif %}">
                        <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
                    </li>
                {% endfor %}
            </ul>

            <hr class="my-6">

            <p class="font-semibold">Clear filters</p>

            <ul>
                <li><a href="{% url 'item:items' %}" class="mt-2 py-3 px-6 inline-block bg-yellow-500 text-lg rounded-xl text-white">Clear</a></li>
            </ul>
        </div>

        <div class="md:col-span-3">
            <div class="grid grid-cols-1 md:grid-cols-3 gap-3">
                {% for item in items %}
                    <div>
                        <a href="{% url 'item:detail' item.id %}">
                            <div class="p-4 md:p-6 bg-white rounded-b-xl">
                                <h2 class="text-xl md:text-2xl">{{ item.name }}</h2>
                                <p class="text-gray-500">Price: {{ item.price }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

items/templates/items/new_item.html
{% extends "base.html" %}

{% block content %}

<div class="w-full md:w-2/3 my-6 p-4 md:p-6 mx-auto rounded-xl bg-gray-100">
    <h1 class="mb-6 text-2xl md:text-3xl">New Item</h1>

    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}

        <div class="space-y-4">
            {{ form.as_p }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mt-6 p-4 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="mt-6 py-3 px-6 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}