core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .forms import LoginForm
from . import views

urlpatterns = [
    path("", views.index, name="home"),
    path("contact/", views.contact, name="contact"),
    path("signup/", views.signup, name="signup"),
    path("login/", auth_views.LoginView.as_view(template_name="core/login.html",authentication_form=LoginForm), name="login"),
] 

items/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('<int:pk>/', views.details, name='detail'),
    path('new/', views.new_item, name='new'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),

]

puddle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("items/", include("items.urls")),
    path("dashboard/", include("dashboard.urls")),
    path('conversation/', include('conversation.urls')),
] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.name

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    username = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'Your username', 'class': 'w-full px-4 py-6 rounded-xl'})
    )

    email = forms.EmailField(
        widget=forms.TextInput(
            attrs={'placeholder': 'Your email', 'class': 'w-full px-4 py-6 rounded-xl'})
    )

    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'placeholder': 'Your password', 'class': 'w-full px-4 py-6 rounded-xl'})
    )

    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'placeholder': 'Confirm your password', 'class': 'w-full px-4 py-6 rounded-xl'})
    )


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'Your username', 'class': 'w-full px-4 py-6 rounded-xl'})
    )

    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'placeholder': 'Your password', 'class': 'w-full px-4 py-6 rounded-xl'})
    )


class ContactForm(forms.Form):
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'Your name', 'class': 'w-full px-4 py-6 rounded-xl'})
    )

    email = forms.EmailField(
        widget=forms.TextInput(
            attrs={'placeholder': 'Your email', 'class': 'w-full px-4 py-6 rounded-xl'})
    )

    message = forms.CharField(
        widget=forms.Textarea(
            attrs={'placeholder': 'Your message', 'class': 'w-full px-4 py-6 rounded-xl'})
    )

core/views.py
from django.shortcuts import render, redirect
from items.models import Category, Item
from .models import Contact
from .forms import SignUpForm, ContactForm
# Create your views here.


def index(request):
    items = Item.objects.filter(is_sold=False).order_by('-created_at')[:6]
    categories = Category.objects.all()
    context = {
        "items": items,
        "categories": categories
    }
    return render(request, "core/index.html", context)


def contact(request):
    form = ContactForm()
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            print("valid")
            form.save()
            return redirect("/")
        else:
            form = ContactForm()
            print("invalid")
            print(form.errors)
    return render(request, "core/contact.html")


def signup(request):
    form = SignUpForm()
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            print("valid")
            form.save()
            return redirect("/login/")
        else:
            form = SignUpForm()
            print("invalid")
            print(form.errors)
    context = {
        "form": form
    }
    return render(request, "core/signup.html", context)

core/templates/core/contact.html
{% extends "base.html" %}

{% block content %}
    <p>Contact</p>
{% endblock %}

core/templates/core/index.html
{% extends "base.html" %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-8 text-2xl md:text-3xl text-center">Newest Items</h2>
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {% for item in items %}
            <div class="mb-6">
                <a href="{% url "item:detail" item.id%}" class="block rounded-xl overflow-hidden bg-white hover:shadow-md">
                    {% if item.images %}
                    <img src="{{ item.images.url }}" alt="{{ item.name }}" class="rounded-t-xl w-full">
                    {% endif %}
                    <div class="p-4 md:p-6 bg-white rounded-b-lg">
                        <h3 class="text-lg md:text-xl font-bold">{{ item.name }}</h3>
                        <p class="text-gray-500">${{ item.price }}</p>    
                    </div>
                </a>
            </div>
          {% endfor %}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-8 text-2xl md:text-3xl text-center">Categories</h2>
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {% for category in categories %}
                <div class="mb-6">
                    <a href="#" class="block rounded-xl overflow-hidden bg-white hover:shadow-md">
                        <div class="p-4 md:p-6 bg-white rounded-b-lg">
                            <h3 class="text-lg md:text-xl font-bold">{{ category.name }}</h3>
                            <p class="text-gray-500">{{ category.items.count }} items</p>    
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

core/templates/core/login.html
{% extends "base.html" %}

{% block content %}
    <div class="w-full sm:w-1/2 my-6 p-4 md:p-6 mx-auto rounded-xl bg-gray-100">
        <h1 class="text-xl md:text-2xl text-center font-bold my-4">Login</h1>

        <form method="post" action=".">
            {% csrf_token %}
        
            <div class="mb-3">
                <label class="block mb-2">Username</label>
                {{form.username}}
            </div>
            <div class="mb-3">
                <label class="block mb-2">Password</label>
                {{form.password}}
            </div>
            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-4 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}
                    {{form.non_field_errors}}
                </div>
            {% endif %}

            <button type="submit" class="bg-teal-500 hover:bg-teal-700 text-white font-bold py-3 px-6 text-lg rounded my-4">Login</button>
        </form>
    </div>
{% endblock %}

core/templates/core/signup.html
{% extends "base.html" %}

{% block content %}
    <div class="w-full sm:w-1/2 my-6 p-4 md:p-6 mx-auto rounded-xl bg-gray-100">
        <h1 class="text-xl md:text-2xl text-center font-bold my-4">Sign Up</h1>

        <form method="post" action=".">
            {% csrf_token %}
            
            <div class="mb-3">
                <label class="block mb-2">Username</label>
                {{form.username}}
            </div>
            <div class="mb-3">
                <label class="block mb-2">Email</label>
                {{form.email}}
            </div>
            <div class="mb-3">
                <label class="block mb-2">Password</label>
                {{form.password1}}
            </div>
            <div class="mb-3">
                <label class="block mb-2">Password Confirmation</label>
                {{form.password2}}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-4 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}
                    {{form.non_field_errors}}
                </div>
            {% endif %}

            <button type="submit" class="bg-teal-500 hover:bg-teal-700 text-white font-bold py-3 px-6 text-lg rounded my-4">Sign Up</button>
        </form>
    </div>
{% endblock %}